feat():terminando testes beneficio
Conexao-Solidaria/consol-crud-java pull request #7
Opened 2024-05-27 20:24 UTC by caioarnonii

2024-05-27 20:27 UTC, caioarnonii commented
.

2024-05-27 20:28 UTC, caioarnonii commented
.

2024-05-27 20:37 UTC, gba-exe requested changes
Favor refazer os pontos comentados.

2024-05-27 20:37 UTC, gba-exe commented on src/main/java/com/consol/api/service/BeneficioService.java
> +    public boolean deletar(int id) {
mudar de boolean para void

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                                .content("{ \"nome\": \"Bolsa família\", \"valor\": 150.0, \"donatario\": {} }"))
formatar o JSON em block para melhor legibilidade

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +            @DisplayName("Se o donatário existir: " +
donatario

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                Donatario donatario = Donatario.builder()
isso tem q ser um beneficio, nao donatario

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                Mockito.when(beneficioService.listarPorDonatario("Donatário X"))
o nome do metodo ta donatario

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                        .thenReturn((List<Beneficio>) donatario);
esta retornando donatario

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                mockMvc.perform(MockMvcRequestBuilders.get(DonatarioEnum.POR_ID.PATH, 1)
o request esta todo errado e esperando um donatario

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +            @DisplayName("Se não houver donatários cadastrados: " +
donatario

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                Mockito.when(beneficioService.listarPorDonatario("Donatário"))
donatario

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                mockMvc.perform(MockMvcRequestBuilders.get(DonatarioEnum.FILTRO.PATH)
donatario

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                mockMvc.perform(MockMvcRequestBuilders.get(DonatarioEnum.FILTRO.PATH)
o enum tem q ser de beneficio, nao donatario, favor criar

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                mockMvc.perform(MockMvcRequestBuilders.post("/beneficios")
nao esta usando o enum

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                mockMvc.perform(MockMvcRequestBuilders.post("/beneficios")
nao esta usando o enum

2024-05-27 20:37 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                mockMvc.perform(MockMvcRequestBuilders.post("/beneficios")
nao esta usando o enum

2024-05-27 20:37 UTC, gba-exe commented on src/main/java/com/consol/api/service/BeneficioService.java
> +    public List<Beneficio> listarPorDonatario(String donatario) {
donatario

2024-05-27 20:53 UTC, caioarnonii commented on src/main/java/com/consol/api/service/BeneficioService.java
> +    public boolean deletar(int id) {
ok

2024-05-27 20:54 UTC, caioarnonii commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                                .content("{ \"nome\": \"Bolsa família\", \"valor\": 150.0, \"donatario\": {} }"))
Ok

2024-05-27 20:58 UTC, caioarnonii commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +            @DisplayName("Se o donatário existir: " +
Ok

2024-05-27 20:59 UTC, caioarnonii commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                Donatario donatario = Donatario.builder()
Ok

2024-05-27 20:59 UTC, caioarnonii commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                Mockito.when(beneficioService.listarPorDonatario("Donatário X"))
Ok

2024-05-27 20:59 UTC, caioarnonii commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                        .thenReturn((List<Beneficio>) donatario);
Ok

2024-05-27 21:00 UTC, caioarnonii commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                mockMvc.perform(MockMvcRequestBuilders.get(DonatarioEnum.POR_ID.PATH, 1)
Ok

2024-05-28 20:22 UTC, gba-exe approved these changes
tudo certo

2024-05-28 20:22 UTC, gba-exe commented on src/test/java/com/consol/api/controller/BeneficioControllerTest.java
> +                                .content("{ \"nome\": \"Bolsa família\", \"valor\": 150.0, \"donatario\": {} }"))
formatar tal qual os testes em familia e donatario

2024-05-28 20:23 UTC, merged